### ISSUE TITLE
Crash RX 5700 XT Sapphire Nitro+

### ISSUE THREAD

**Issue by nicolas1410** [BeamMW/beam#1779] opened 2021-05-23 06:23 UTC
Hey,

For a while I get this crash for no reason. Can be after 10 minutes and can run for hours before it happens.

Any idea from what it is ?

Here the screen:
https://prnt.sc/13akid6

**Comment by r45ku1** [comment] 2021-05-25 07:03
Lower your clock speeds down and set your voltage 1000mV

Tune your graphics card from low clocks upwards in small  increments. The error is caused by one of three things

A) your clock settings are too high
B) you are trying to perform other tasks at same time as mining (don't)
C) the GPU is faulty.

**Comment by gingervik** [comment] 2021-06-14 06:38
@nicolas1410 hi. do you still have this issue?

**Comment by nicolas1410** [comment] 2022-08-19 11:41
Yes it happens sometimes but less than before

**Comment by beam-mw** [comment] 2022-10-02 08:50
Can we close this issue? Is there somethings else we can do here?

**Closed** 2022-10-02 09:08 UTC
