### ISSUE TITLE
seed restore problems

### ISSUE THREAD

**Issue by pawsme** [BeamMW/beam#516] opened 2019-03-12 05:57 UTC
I've experianced two problems this week while doing wallet seed restores.

1. Zero beam shown in wallet after restore. 
2. Incorrect beam amount shown after restore.

V1.2.4419
Windows desktop wallet
Wallet Block height current

**Comment by Sergei-Beam** [comment] 2019-03-12 10:02
@pawsme hi
1. sound like smth impossible. this means that your seed incorrect
if you use correct seed with YOUR node everything should be restored
2. it might be related to cloned wallets, 
you shouldn't copy and transmit the wallet.db to the different machine and run the same wallet.db on two or more machines at the same time

**Comment by pawsme** [comment] 2019-03-13 03:52
I'm not copying wallet.db. I'm having beam desktop wallet create wallet.db using seed phrase. Tried several times with multiple seeds.

**Comment by disa59** [comment] 2019-03-15 06:01
Same problem!
I forgot password and tried to reinit wallet with 12 word phrase after delete wallet.db. It was reinitialized sucsessfully. But now it has another adress for receiving coins, differ from previos. How could i get coins from pool whitch was gained with previous wallet number? And also it has zero balance! but pool says that several coins was paied.

**Comment by pawsme** [comment] 2019-03-15 06:14
I don't think restoring your wallet with seed will restore your addresess but it should restore your beam balance. If you had a beam balance in your inaccessible wallet and your seed phrase didnt restore that beam, then you do have the same problem I've run into.

**Comment by disa59** [comment] 2019-03-15 06:21
i'm not sure that i have non zero balans on my previous wallet! I didn't run it for a long time and so didn't sync it. But pool shows my that they sent coins on my previous receiving adress.

**Comment by pawsme** [comment] 2019-03-15 06:25
Maybe discord support channel would be good place for some assistance with your situation.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rgsnedds** [comment] 2019-03-15 18:50
> i'm not sure that i have non zero balans on my previous wallet! I didn't run it for a long time and so didn't sync it. But pool shows my that they sent coins on my previous receiving adress.

If you didn't sync your wallet, then any funds which might have been transferred to it, would not have been received and would have reverted back to the sender wallet.
Both sender and receiver need to be online (currently within the same two hour timescale) for the transaction to be successful.

Your coins will have gone back to wherever they were sent from.

**Comment by rgsnedds** [comment] 2019-03-15 18:51
> I'm not copying wallet.db. I'm having beam desktop wallet create wallet.db using seed phrase. Tried several times with multiple seeds.

^ several times with multiple seeds. This won't restore any previous wallet.

**Comment by pawsme** [comment] 2019-03-15 18:57
I know the addresses won't be restored by using seed. I've deleted my wallet.db and used the seed restore function. I've repeated the problem i have with multiple seeds. Zero beam balance or incorrect beam balance is what I've experianced after doing a seed restore.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by gingervik** [comment] 2019-03-19 05:48
hello @pawsme 
seems like your wallet seed is incorrect. please, contact our support channel in Telegram to check your logs 
https://t.me/BeamSupport

**Comment by pawsme** [comment] 2019-03-28 00:47
Seed phrase is correct. Seems like a problem with the wallets ability to discover utxo's.

I just tried this again today. Deleted wallet.db file then restored seed

Success, beam restored, on the Windows 10 PC beam wallet that originally created the seed.

Moving over to a different Windows 10 PC. Zero Beam restored, rescan button didn't fix. Deleting blockchain files and re syncing didn't fix.

Using recommended local node.

I've recreated this same problem with a few seeds. 

Maybe its just my PCs.......

**Comment by gingervik** [comment] 2019-03-28 07:14
@Jagor21 please, chech it with user

**Comment by pawsme** [comment] 2019-03-30 09:14
Working.
Its not very intuitive at the moment but the rescan button in settings does work. After pressing it, it appears you have to remain within the setting screen for a while. After leaving the settings menu the proper beam amount is shown in the wallet.

**Comment by gingervik** [comment] 2019-04-01 07:49
@pawsme rescan button will be remove soon from settings.
It's strage that your coins were not restored during restore process but appeared after rescan

**Comment by Jagor21** [comment] 2019-04-01 08:28
@pawsme please confirm if the issue is gone.

**Closed** 2019-05-06 08:27 UTC
