### ISSUE TITLE
Atomic Swap support in Desktop Wallet

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam#486] opened 2019-02-24 08:14 UTC
![v3-wallet-one-coin](https://user-images.githubusercontent.com/37414225/53296830-c234f100-381c-11e9-8c49-16d3ad3ebb53.png)
![v3-wallet](https://user-images.githubusercontent.com/37414225/53296831-c234f100-381c-11e9-80b1-d99ed60aaeb3.png)
![v3-wallet-one-transaction](https://user-images.githubusercontent.com/37414225/53296832-c234f100-381c-11e9-9b0f-ee21ae1cb05e.png)

https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889?seid=5bb2fd433aa99611f227c308

https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889?seid=5bd18fa191d4f20f4973514c

https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889?seid=5bd18fb791d4f20f49735319

**Comment by chapati** [comment] 2019-07-20 13:51
There are separate tasks for some parts of this big task already

#759 Create UI for the swap offer
#760 Create UI for Swap send
#770 Add balances of currencies for swap to Available panel

**Comment by alexandrashelenkova** [comment] 2019-09-09 10:44
Duplicate of https://github.com/BeamMW/beam/issues/849

**Closed by alexandrashelenkova** 2019-09-09 10:44 UTC
