### ISSUE TITLE
UI Wallet - add the list of peers to the settings if run specific remote node

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#562] opened 2019-03-26 12:51 UTC
When user run the Wallet with a connection to specific remote node he should be able to switch from remote to local without any problems. Currently, the problem is a blank list of peers 
![photo_2019-03-26_15-35-54](https://user-images.githubusercontent.com/44496108/54997855-c00db000-4fdd-11e9-96fe-50a1e977b03e.jpg)

We should add the list of peers to the settings if wallet run as specific remote node like it's done for other types of connections
![image](https://user-images.githubusercontent.com/44496108/54998108-57730300-4fde-11e9-96d0-5dfe8ea5eb1e.png)

**Comment by gingervik** [comment] 2019-06-20 09:31
Duplicate of #159

**Closed by gingervik** 2019-06-20 09:31 UTC
Labels: bug, help wanted, ux
