### ISSUE TITLE
Green indicator when status is "System time is not synchronized"

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1202] opened 2019-12-20 08:00 UTC
Indicator should be red because Wallet cannot be connected to node when it has such status as "System time is not synchronized"
![Snag_14f41310](https://user-images.githubusercontent.com/51320829/71239471-b10f2080-2317-11ea-9b28-2f34ac4c2688.png)

**Comment by anatolse** [comment] 2020-01-28 15:03
duplicate of #1196

**Closed by anatolse** 2020-01-28 15:03 UTC
Labels: UI wallet, bug
