### ISSUE TITLE
Payment proof: the proof should be generated only when Kernel ID was successfully registered in the blockchain (CLI wallet)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#547] opened 2019-03-21 13:47 UTC

**Comment by gingervik** [comment] 2019-03-22 09:41
@sasha-abramovich are you talking about UI wallet or cli?

**Comment by sasha-abramovich** [comment] 2019-03-25 08:00
@gingervik CLI wallet (title updated)

**Comment by gingervik** [comment] 2019-05-02 09:56
duplicate of #615

**Closed by gingervik** 2019-05-02 09:56 UTC
