### ISSUE TITLE
UI Wallet - Add "reason" for failed transactions

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#328] opened 2019-01-10 10:26 UTC
We need to show user a reason when transaction is failed.
@sasha-abramovich please, provide a design for it (tooltip or some additional info in transaction's details)
Thank you

**Comment by sasha-abramovich** [comment] 2019-01-10 10:37
@alexandrashelenkova please provide the screen and assign to @anatolse when done. should be attended after the expiration.

**Comment by alexandrashelenkova** [comment] 2019-01-11 06:46
We can show the reason under status in transaction list (same as description under status on utxo list screen).
zpl.io/bWLWYDM

**Comment by sasha-abramovich** [comment] 2019-01-11 06:52
@alexandrashelenkova the reason can be a longer string - what can we do if so? expand on mouseover? show the full value in the extended transaction details? anything else?

**Comment by alexandrashelenkova** [comment] 2019-01-11 06:55
@sasha-abramovich how much longer? Do you have failure reasons examples? Might be short one here and "full" one somewhere on detailed view - it depends on how actual reasons would looks like.

**Comment by sasha-abramovich** [comment] 2019-01-11 06:58
Sadly, we don't have the full list of errors at this point, right @gingervik?

Just a wild guess: "Failed connect to the node", "Transaction aborted as the peer didn't came online"

**Comment by alexandrashelenkova** [comment] 2019-01-11 07:41
If so it's better to show only "failed" in transaction list and reason in details. Screen updated.

**Comment by sasha-abramovich** [comment] 2019-01-11 12:45
https://zpl.io/bWLWYDM 
See "transaction status" in the extended transaction view

**Comment by jurijakimuk** [comment] 2019-01-25 11:06
@anatolse Hi, as discussed in person, please see the wallet.db attached for the analysis. I was not able to see the new changes in the UI on 4311 (master). Thank you.
[wallet.zip](https://github.com/BeamMW/beam/files/2795774/wallet.zip)

**Comment by anatolse** [comment] 2019-01-29 12:49
please, recheck, cannot reproduce

**Comment by jurijakimuk** [comment] 2019-01-30 09:12
Tested on 4335, master.
There's no error message for outgoing failed transactions, although for the incoming there is one.
![outgoing_no_error_msg](https://user-images.githubusercontent.com/41323026/51970415-e86aa980-2487-11e9-96c1-a52a03941cab.png)
![incoming_error_msg_exist](https://user-images.githubusercontent.com/41323026/51970417-eb659a00-2487-11e9-9a2d-b38a801200e9.png)
@anatolse Please, take a look.
Logs: 
[logs.zip](https://github.com/BeamMW/beam/files/2811755/logs.zip)

**Comment by jurijakimuk** [comment] 2019-02-05 10:06
Tested on master, 4355. Works OK. Closing.

**Comment by jurijakimuk** [comment] 2019-02-06 14:21
Tested on 4362, Reasons for failed and expired transactions show up.

**Closed by jurijakimuk** 2019-02-06 14:21 UTC
