### ISSUE TITLE
Wallet CLI: displayed amount  unit error

### ISSUE THREAD

**Issue by suyanlong** [BeamMW/beam#366] opened 2019-01-18 08:29 UTC
in mainnet branch:
The first one, actually I used 0.00000005beams, but it actually showed 0.5beams,which was wrong, etc.

![image](https://user-images.githubusercontent.com/16421423/51374360-c135e300-1b3d-11e9-9b8b-34889afa0363.png)

**Comment by nesbox** [comment] 2019-01-18 09:54
duplicate of #272

**Closed by nesbox** 2019-01-18 09:54 UTC
