### ISSUE TITLE
Incorrect icon is used in Main screen ->transactions

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#550] opened 2019-03-24 09:14 UTC
Incorrect icon is used in Main screen ->transactions 
![image](https://user-images.githubusercontent.com/45590119/54877222-3e265700-4e24-11e9-8f96-5a356468c094.png)

**Comment by kaminskyelina** [comment] 2019-03-24 09:14
Should be:

**Comment by kaminskyelina** [comment] 2019-03-24 09:14
![image](https://user-images.githubusercontent.com/45590119/54877358-04eee680-4e26-11e9-8b03-b43133e8b088.png)

**Comment by gingervik** [comment] 2019-03-25 07:45
duplicate of #476

**Closed by gingervik** 2019-03-25 07:45 UTC
Labels: bug, ux
