### ISSUE TITLE
Ubuntu 18.10: cmake Policy CMP0071 is not set

### ISSUE THREAD

**Issue by frankcoderL** [BeamMW/beam#232] opened 2018-12-24 15:24 UTC
**Bug description**
Ubuntu 18.10 cmake Policy CMP0071 is not set

**To Reproduce**
Compile on Ubuntu 18.10 (cosmic)
git clone https://github.com/BeamMW/beam.git

**Platform and build**
* Linux 
* Ubuntu 18.10 (cosmic)
* BEAM Build number: current GIT

````
$ cmake -DCMAKE_BUILD_TYPE=Release . && make -j4
-- Found Git: /usr/bin/git (found version "2.19.1") 
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
BRANCH_NAME: master
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
BEAM_VERSION: 1.0.3783
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")  
-- Using OpenSSL 1.1.1
-- Configuring done
CMake Warning (dev) in ui/CMakeLists.txt:
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the GENERATED source file(s):

    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_dashboard_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_addresses_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_start_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_utxo_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_root_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_wallet_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_notification_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_restore_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_main_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_info_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_settings_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_PrimaryButton_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_DefaultButton_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_TxFilter_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_TableItem_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_SvgImage_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_Style_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_SFFontLoader_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_AddressTable_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_CustomTableView_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_SFTextInput_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_ConfirmationDialog_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_ChangePasswordDialog_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_StatusBar_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_AddressComboBox_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_SFLabel_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_AvailablePanel_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_CustomSwitch_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_CustomComboBox_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_LogoComponent_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_CustomProgressBar_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_SecondaryPanel_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_CustomRadioButton_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_CustomCheckBox_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_ContextMenu_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_FeeSlider_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_CustomToolButton_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_SFText_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_Led_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_SecurityNote_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/view_controls_CustomButton_qml.cpp"
    "/home/lcoder/source/20181224_BeamGit/beam/ui/qmlcache_loader.cpp"

  from processing by AUTOMOC.  If any of the files should be processed, set
  CMP0071 to NEW.  If any of the files should not be processed, explicitly
  exclude them by setting the source file property SKIP_AUTOMOC:

    set_property(SOURCE file.h PROPERTY SKIP_AUTOMOC ON)

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/lcoder/source/20181224_BeamGit/beam
Scanning dependencies of target qrcode
Scanning dependencies of target sqlite
[  0%] Generating quazip/moc_minizip_crypt.cpp
...
...
...
100%] Built target wallet_api
[100%] Linking CXX executable BeamWallet
[100%] Built target beam-wallet-ui
$ 


$ cmake --version
cmake version 3.12.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$


$ cmake --help-policy CMP0071
CMP0071
-------

Let ``AUTOMOC`` and ``AUTOUIC`` process
``GENERATED`` files.

Since version 3.10, CMake processes **regular** and ``GENERATED``
source files in ``AUTOMOC`` and ``AUTOUIC``.
In earlier CMake versions, only **regular** source files were processed.
``GENERATED`` source files were ignored silently.

This policy affects how source files that are ``GENERATED``
get treated in ``AUTOMOC`` and ``AUTOUIC``.

The ``OLD`` behavior for this policy is to ignore ``GENERATED``
source files in ``AUTOMOC`` and ``AUTOUIC``.

The ``NEW`` behavior for this policy is to process ``GENERATED``
source files in ``AUTOMOC`` and ``AUTOUIC`` just like regular
source files.

.. note::

  To silence the CMP0071 warning source files can be excluded from
  ``AUTOMOC`` and ``AUTOUIC`` processing by setting the
  source file properties ``SKIP_AUTOMOC``, ``SKIP_AUTOUIC`` or
  ``SKIP_AUTOGEN``.

Source skip example::

 # ...
 set_property(SOURCE /path/to/file1.h PROPERTY SKIP_AUTOMOC ON)
 set_property(SOURCE /path/to/file2.h PROPERTY SKIP_AUTOUIC ON)
 set_property(SOURCE /path/to/file3.h PROPERTY SKIP_AUTOGEN ON)
 # ...

This policy was introduced in CMake version 3.10.  CMake version
3.12.1 warns when the policy is not set and uses ``OLD`` behavior.
Use the ``cmake_policy()`` command to set it to ``OLD`` or ``NEW``
explicitly.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.

$
````

**Comment by gingervik** [comment] 2019-03-05 11:45
@nesbox please, help

**Comment by nesbox** [comment] 2019-03-06 12:09
It's not a bug, just warning, anyway we can fix it.

**Comment by jurijakimuk** [comment] 2019-03-12 11:23
Tested after the fix. No warning is shown. Closing.

**Closed by jurijakimuk** 2019-03-12 11:23 UTC
