### ISSUE TITLE
Add Atomic Swap tx to Beam Wallet Transactions list

### ISSUE THREAD

**Issue by beggsdl** [BeamMW/beam#1302] opened 2020-03-06 22:48 UTC
**Feature title**
Add the receiving and sending of Beam through Atomic Swaps to the Wallet Transactions list.

**Describe the current situation we have**
Currently, you are not able to get a full picture of Beam movement by just looking at the Wallet Transactions listing.  You have to go look at the Swap Transactions page to see what Beam has moved in or out through Atomic Swaps.  Likewise, the current Export does not include Beam involved in Atomic Swap, so exporting and then adding up your transactions may not give you the correct balance if you have done swaps.

**Describe the solution you'd like**
Include Beam sent or received through Atomic Swaps to the Wallet Transactions list.  The status for these could be something like "swap sent" and "swap received" to distinguish these from regular transactions.  Also, include Atomic Swap Beam in the Wallet Transaction export so a user can have the full picture of their Beam transaction history.  I could also see adding an Export button to the Swaps Transactions screen to export all of the swap transaction information, including the non-Beam coin information.

I am running Win10 with wallet version 4.1.6978.

**Comment by sasha-abramovich** [comment] 2020-03-11 06:20
This is a good idea, however, nothing comes easy. If we'll show everything on the first page, it will be less intuitive for the users to differentiate between the currencies that we can send/receive (e.g. Beam currently and confidential assets later) and the currencies we can only swap (e.g. BTC/LTC/QTUM). In addition, we'd need to always show all the possible actions as buttons: e.g. send, receive, create swap offer, swap, while only some are applicable to some currencies. Again, it is a great idea to have everything syndicated at a single place, we are still thinking about how to make it right. It will take time. Meanwhile, I'll close this item as a duplicate of something we are already considering.

**Closed by sasha-abramovich** 2020-03-11 06:20 UTC
