### ISSUE TITLE
When user click on X wallet should minimize to Dock/Tray

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#27] opened 2018-11-08 12:01 UTC
Wallet should remain online by default to accept all incoming transactions and to keep the coupled node (if attached) in operational state.

**Comment by alexandrashelenkova** [comment] 2019-07-09 08:47
Duplicate of https://github.com/BeamMW/beam/issues/374

**Closed by alexandrashelenkova** 2019-07-09 08:47 UTC
Labels: help wanted, ux
