### ISSUE TITLE
Settings aren't saved

### ISSUE THREAD

**Issue by omrierez** [BeamMW/beam#289] opened 2019-01-04 14:18 UTC
**Bug title** Settings value doesn&#39;t being saved **Bug description** After changing the &quot;Lock Screen in&quot; setting it always goes back to &quot;never&quot; after a restart of the desktop wallet **To Reproduce** Steps to reproduce the behavior: 1. open the desktop wallet on mac 2. Open the settings screen 3. change &quot;lock screen&quot; to one of the values 4. click apply 5. close the wallet 6. open the wallet 7. open the settings screen 8. &quot;lock screen&quot; is on &quot;never&quot; **Current behavior** The changed value isn&#39;t saved **Expected behavior** The changed value should be saved **Platform and build** Mac * BEAM Build number 1.0.33976

**Comment by gingervik** [comment] 2019-01-04 15:47
@omrierez hello
cannot reproduce it acc to your steps
check video pls
[289.zip](https://github.com/BeamMW/beam/files/2727546/289.zip)

**Comment by gingervik** [comment] 2019-01-08 06:13
@omrierez 
hi
did you reproduce it again?
have you a 100% scenario to do it or we can close this issue?

**Comment by gingervik** [comment] 2019-01-18 05:51
there is no response from user. QAs cannot reproduce it

**Comment by locomo** [comment] 2019-03-11 16:48
I am experiencing this issue
MacOS wallet version 1.2.4419
MacOS High Sierra 10.13.6

steps to reproduce are exact same as @omrierez described in initial post

**Comment by gingervik** [comment] 2019-03-13 05:01
reproduced on mac os 10.14.3
wallet wersion 1.2.4419

**Comment by gingervik** [comment] 2019-03-29 09:30
`Created by TestQuality - Linked to TestQuality.com defect D6. Do not remove or edit.` [D6](https://beam.testquality.com/project/5267/result/1067095/defect/3810)

**Comment by Sergei-Beam** [comment] 2019-04-10 07:18
checked

**Closed by Sergei-Beam** 2019-04-10 07:18 UTC
Labels: TestQuality, bug, ux

**Comment by locomo** [comment] 2019-04-21 15:47
I'm still seeing this
MacOS wallet version 2.0.4739
MacOS Mojave 10.14.4

After changing and saving the setting if you quit and reopen the wallet the 'Lock screen in' setting reverts to 'never'

**Comment by gingervik** [comment] 2019-04-21 15:59
@locomo this fix is not released yet. Sprint is in progress

**Comment by locomo** [comment] 2019-04-22 13:24
sorry, my bad .. i saw the ticket had closed and assumed it was in the latest release
