### ISSUE TITLE
No password required to turn off transactions password requirement 

### ISSUE THREAD

**Issue by gussulliman** [BeamMW/beam#707] opened 2019-06-08 16:50 UTC
**No password required to turn off transactions password requirement**
To change the settings for password requirement to off, it needs to have the password input. 

**Bug description**
When a user sets a password requirement for sending transactions to off, there is no requirement to input password, which essentially leaves the feature obsolete. 

**To Reproduce**
Steps to reproduce the behaviour:
1. turn 'Ask password for every sending transaction' on
2. sending requires a password 
3. turn 'Ask password for every sending transaction' off, no password needed to change this, and now no passworded needed to send a transaction 

**Current behaviour**
no password required to change password setttings.

**Expected behaviour**
A password required to change this password setting .

**Platform and build**
* Mac Gui wallet, 2.1.4910 - potentially all gui wallets

**Comment by gingervik** [comment] 2019-06-10 07:27
hi @gussulliman 
this is a duplicate of https://github.com/BeamMW/beam/issues/692

**Closed by gingervik** 2019-06-10 07:27 UTC
