### ISSUE TITLE
Add toggle switch for "Address expiration" in notification settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1403] opened 2020-04-28 08:51 UTC
Please add toggle switch for "Address expiration"
https://zpl.io/VQ5jQZR

Also change "Wallet version" to "Wallet updates"

**Comment by chapati** [comment] 2020-06-08 11:26
Closing as duplicate of #1479

**Closed by chapati** 2020-06-08 11:26 UTC
Labels: UI wallet, ux
