### ISSUE TITLE
Main screen (new version)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#850] opened 2019-09-09 08:10 UTC
New version of main screen is here:
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5d6f86f6952969189fd39ddf

Please pay attention to notes on screens (ONLY violet comments).
<img width="123" alt="Screenshot 2019-09-09 at 16 53 59" src="https://user-images.githubusercontent.com/7249484/64519799-71ec2f00-d327-11e9-9658-4ab45581b9d1.png">
 
All balances conditions are here https://zpl.io/aN1gBnD

**Comment by gingervik** [comment] 2019-09-09 08:37
@alexandrashelenkova is it duplicate of #833 ?

**Comment by chapati** [comment] 2019-09-20 10:20
Nee to fill the following funcsi in WalletViewModel:

   double  beamAvailable() const;
    double  beamReceiving() const;
    double  beamSending() const;
    double  beamLocked() const;
    double  beamLockedAtomic() const;
    double  beamLockedMaturing() const;
    double  beamReceivingChange() const;
    double  beamReceivingIncoming() const;

**Comment by iamien1993** [comment] 2019-10-01 10:16
reports are created: 
https://github.com/BeamMW/beam/issues/944
https://github.com/BeamMW/beam/issues/945

**Comment by iamien1993** [comment] 2019-10-02 09:26
checked (except "Locked" block)
v 4.0.6264

**Comment by iamien1993** [comment] 2019-10-02 09:37
"Locked" block (Maturing) checked
v 4.0.6264

**Closed by iamien1993** 2019-10-02 09:37 UTC
Labels: task, ux
