### ISSUE TITLE
Time estimation in downloading blocks is not real

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#373] opened 2019-01-20 09:42 UTC
**Bug title**
Time estimation in downloading blocks is not real

**Bug description**
Time estimation in downloading blocks is not accurate and not real

Option A: fix the time estimation and make it correct.
Option B: Change the text “Downloading block X out of Y”, where X – currently downloaded block, Y – total blockchain height. Needs to be tested for large block numbers (max is 69,904,800) so that it fits. 
Option C: combine A + B
Option B is much preferable – easy to implement and test. Correct time estimation in this case will be very hard to do since network conditions are hard to predict.

*Reported by Alexander Zaidelson

**Comment by gingervik** [comment] 2019-01-20 16:06
duplicate of https://github.com/BeamMW/beam/issues/206

**Closed by gingervik** 2019-01-20 16:06 UTC
